#!/usr/bin/env python3
"""
自动生成 HTML 索引页（v2 修复子目录问题）
遍历指定目录下所有 .html/.htm 文件，生成包含相对链接的索引页。
确保所有文件（包括深层子目录）都能被前端爬虫发现。
"""

import sys
from pathlib import Path
import re
import argparse

def extract_title(file_path: Path) -> str:
    """提取 HTML 文件的 <title> 内容，若失败返回文件名"""
    try:
        text = file_path.read_text(encoding='utf-8', errors='ignore')
        match = re.search(r'<title[^>]*>(.*?)</title>', text, re.IGNORECASE | re.DOTALL)
        if match:
            return match.group(1).strip()
    except Exception:
        pass
    return file_path.name

def generate_index(scan_dir: str, output_path: str, exclude_self: bool = True):
    scan_dir = Path(scan_dir).resolve()
    output_file = Path(output_path).resolve()
    output_dir = output_file.parent

    if not scan_dir.exists():
        print(f'❌ 错误：扫描目录不存在 "{scan_dir}"')
        sys.exit(1)

    # 使用 rglob 递归查找所有 html 文件
    pattern = '**/*.html'
    all_html = [p for p in scan_dir.rglob('*.html')]
    all_html += [p for p in scan_dir.rglob('*.htm')]
    # 去重并排序
    all_html = sorted(set(all_html))

    # 排除自身
    if exclude_self:
        all_html = [p for p in all_html if p.resolve() != output_file]

    if not all_html:
        print(f'⚠️ 在 {scan_dir} 中未找到任何 .html 文件。')
        # 仍然生成一个空索引
        links = []
    else:
        print(f'🔍 找到 {len(all_html)} 个 HTML 文件：')
        links = []
        for html_file in all_html:
            try:
                # 计算相对路径（相对于输出索引所在的目录）
                rel_path = html_file.relative_to(output_dir)
                # 转换为 POSIX 风格（URL 标准）
                rel_url = rel_path.as_posix()
                title = extract_title(html_file)
                links.append((rel_url, title, html_file))
                print(f'   ├─ {rel_url}  →  "{title}"')
            except ValueError as e:
                print(f'   ⚠️ 无法计算相对路径，跳过：{html_file} ({e})')

    # 生成 HTML
    links_html = ''
    for href, title, _ in links:
        # 安全转义
        safe_href = href.replace('&', '&amp;').replace('"', '&quot;')
        safe_title = title.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        links_html += f'            <li><a href="{safe_href}">{safe_title}</a></li>\n'

    html_content = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML 文件索引（自动生成）</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #333; }}
        ul {{ list-style: none; padding: 0; }}
        li {{ margin: 8px 0; }}
        a {{ color: #4f6ef7; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .footer {{ margin-top: 30px; font-size: 0.85em; color: #888; }}
    </style>
</head>
<body>
    <h1>📁 HTML 文件索引</h1>
    <p>此索引由脚本自动生成，共包含 {len(links)} 个 HTML 文件。</p>
    <ul>
{links_html}
    </ul>
    <div class="footer">Generated by generate_index.py</div>
</body>
</html>'''

    # 写入
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(html_content, encoding='utf-8')
    print(f'\n✅ 索引生成成功：{output_file}')
    print(f'   包含 {len(links)} 个链接，覆盖了所有子目录中的 HTML 文件。')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='生成 HTML 文件索引页（v2）')
    parser.add_argument('--dir', default='./html', help='要扫描的目录（默认：./html）')
    parser.add_argument('--output', default='./html/index.html', help='输出的索引文件路径（默认：./html/index.html）')
    parser.add_argument('--include-self', action='store_true', help='是否包含自身链接')
    args = parser.parse_args()

    generate_index(args.dir, args.output, exclude_self=not args.include_self)
